### ISSUE TITLE
Instructions are broken, some links are death. 

### ISSUE THREAD

**Issue by daniel-farina** [LambdaTest/webdriverio-selenium#8]
Hello! 

All links here are broken:
<img width="969" alt="image" src="https://user-images.githubusercontent.com/13665117/173412266-d2a42492-9d62-4213-a7a7-a2332681ee91.png">

The instructions on the official site do not work, several errors. I would recommend running through the setup one time on a clean environment as this becomes a turn off from using the product.  I'm really excited to test this product. 

![image](https://user-images.githubusercontent.com/13665117/173412515-e4270eff-4d3b-4d2f-8d89-d9b21b8d0260.png)
This part also does not work, multiple errors, missing libraries, etc.

**Comment by 4DvAnCeBoY** [comment]
Hi @daniel-farina,

This repo only works for `webdriverio` version 5.x. 
Please refer the latest repo: https://github.com/LambdaTest/webdriverio-selenium-sample
